// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2j_50dOyg4faBaIqkf7r2C2ZF4Y9Of4s',
    appId: '1:86838221971:android:38d00c48213c7c0b904166',
    messagingSenderId: '86838221971',
    projectId: 'recipe-archive-v2',
    storageBucket: 'recipe-archive-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ3DYfwSuTjgUcpqs195naWjHXiv_VYhk',
    appId: '1:86838221971:ios:f11e0515576211df904166',
    messagingSenderId: '86838221971',
    projectId: 'recipe-archive-v2',
    storageBucket: 'recipe-archive-v2.appspot.com',
    androidClientId: '86838221971-3v7oclu7md68piimlupbd2g1l11ojrkd.apps.googleusercontent.com',
    iosClientId: '86838221971-debf9ob3oq689qbt7jpisf4p8e587l7l.apps.googleusercontent.com',
    iosBundleId: 'com.cowbraingames.recipeArchive',
  );
}
