// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm101OOFidmcWkus0MJ3jXvrzESgpXkQY',
    appId: '1:507431116783:web:7657717b79f13743e6601a',
    messagingSenderId: '507431116783',
    projectId: 'recipe-archive-ee027',
    authDomain: 'recipe-archive-ee027.firebaseapp.com',
    storageBucket: 'recipe-archive-ee027.appspot.com',
    measurementId: 'G-46S97M3M4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVtci12ItO3kENYkY7TXW7qMm7LKTlY4k',
    appId: '1:507431116783:android:738d83e09978ee18e6601a',
    messagingSenderId: '507431116783',
    projectId: 'recipe-archive-ee027',
    storageBucket: 'recipe-archive-ee027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSOSH8hIzLO9Th_74Z-pX_f7Va4jTF3es',
    appId: '1:507431116783:ios:827c9027c315b7f1e6601a',
    messagingSenderId: '507431116783',
    projectId: 'recipe-archive-ee027',
    storageBucket: 'recipe-archive-ee027.appspot.com',
    iosClientId: '507431116783-4bn1peane6p44khf6l34m2pjikk84r2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeArchive',
  );
}
